Represent hierarchical commits properly
Lubrsi/serenityos-web-changelog pull request #6
Opened 2021-12-01 21:56 UTC by kleinesfilmroellchen

It's common practice to use hierarchical categories for commits,
especially in Kernel and all categories that have tests. An example
would be "Kernel/X86/PCI". These categories are now represented with
hierarchical accordions, which can also arbitrarily nest. Due to the
nature of non-<li>'s in <ul>'s, the sub-categories appear after all the
direct commits of the categories. In my opinion however, that's one of
the best designs and it doesn't need to change.

For this change, the entire category system was moved to a Category
class which keeps track of this hierarchy during page generation.

An auxiliary change is case-insensitiveness for categories. Especially
programs that have a lower-case name are commonly written that way by
some contributors, which would previously make them appear under
separate categories.

2021-12-01 22:53 UTC, Lubrsi commented on index.js
> +                    this['x' + lcCategory].push(commit);
```suggestion
                    const lcCategoryProperty = 'x' + lcCategory;
                    const hasCategory = this[lcCategoryProperty] !== undefined;
                    if (!hasCategory) this[lcCategoryProperty] = new Category(this, category);
                    this[lcCategoryProperty].push(commit);
```

2021-12-02 14:01 UTC, Lubrsi requested changes
Functionally looks good. I like the move to private class fields and the use of the `Map`. I especially like the use of `get` methods :)

This is mostly style comments with a few functional changes sprinkled in, the big one being removing `extends Array` as I don't think it's used any more.

A general style comment: while it's not enforced by CI, please run prettier on the file :)

2021-12-02 14:01 UTC, Lubrsi commented on index.js
> +            for (let k of this.#subCategories.keys()) allKeys.push(k);
This can be achieved via the spread operator.
```suggestion
            const allKeys = [...this.#subCategories.keys()];
```

2021-12-02 14:01 UTC, Lubrsi commented on index.js
> +                    this.#subCategories.get(firstSubCategory.toLowerCase()).insertInto(commit, [lowerCategories]);
```suggestion
                    const lcFirstSubCategory = firstSubCategory.toLowerCase();
                    if (!this.#subCategories.has(lcFirstSubCategory))
                        this.#subCategories.set(lcFirstSubCategory, new Category(this, firstSubCategory));
                    this.#subCategories.get(lcFirstSubCategory).insertInto(commit, [lowerCategories]);
```

2021-12-02 14:01 UTC, Lubrsi commented on index.js
> +                validSelectorCategory = "i" + validSelectorCategory;
```suggestion
            if (startsWithNumberRegex.test(validSelectorCategory)) {
                // Selectors starting with a number are invalid. Just prepend an 'i' to counteract it.
                validSelectorCategory = "i" + validSelectorCategory;
            }
```

2021-12-02 14:01 UTC, Lubrsi commented on index.js
> +                if (lcCategory.indexOf("/") < 0) {
```suggestion
                if (category.indexOf("/") < 0) {
                    const lcCategory = category.toLowerCase();
```

2021-12-02 14:01 UTC, Lubrsi commented on index.js
> +            super();
As it no longer inherits from `Array`:
```suggestion
```

2021-12-02 14:01 UTC, Lubrsi commented on index.js
> +    class Category extends Array {
It doesn't look like anything uses `Category` as an `Array` now.
```suggestion
    class Category {
```

2021-12-02 14:01 UTC, Lubrsi commented on index.js
> +            let validSelectorCategory = this.name.replace(invalidSelectorCharacters, "");
```suggestion
            const validSelectorCategory = this.name.replace(invalidSelectorCharacters, "");
```

2021-12-02 14:01 UTC, Lubrsi commented on index.js
> +                let validSelectorCategory = category.validSelector;
```suggestion
                const validSelectorCategory = category.validSelector;
```

2021-12-02 14:01 UTC, Lubrsi commented on index.js
> +
Since `Category` will no longer inherit `Array`, this has to be removed. I don't think this does anything anyway with the move to `#commits` and `#subCategories`
```suggestion
```

2021-12-02 14:01 UTC, Lubrsi commented on index.js
> +            return allKeys.sort(([left], [right]) =>
This will only sort based on the first character of the subcategory.
```suggestion
            return allKeys.sort((left, right) =>
```

2021-12-02 14:16 UTC, kleinesfilmroellchen commented on index.js
> +            for (let k of this.#subCategories.keys()) allKeys.push(k);
Did I mention my JS was rusty?

2021-12-02 14:26 UTC, kleinesfilmroellchen commented on index.js
> +
We still want to sort the commits, so I've moved that to a `this.#commits.sort()`.

2021-12-02 14:26 UTC, kleinesfilmroellchen commented on index.js
> +            return allKeys.sort(([left], [right]) =>
A leftover from some temporary map testing thing I did :^)

2021-12-02 14:31 UTC, Lubrsi commented on index.js
> +                        );
```suggestion
                    if (!this.#subCategories.has(lcFirstSubCategory)) {
                        this.#subCategories.set(
                            lcFirstSubCategory,
                            new Category(this, firstSubCategory)
                        );
                    }
```

2021-12-02 14:37 UTC, Lubrsi approved these changes

2021-12-02 14:37 UTC, merged